# Generated by Django 4.2.7 on 2023-11-24 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
